# Define the default driver
# webdriver.driver=htmlunit
# Appears at the top of the reports
# Root package for any JUnit acceptance tests
# serenity.test.root=net.thucydides.showcase.junit.features
# Customise your requirements hierarchy
# serenity.requirement.types=feature, story
# Run the tests without calling webdriver - useful to check your JBehave wireing
# serenity.dry.run=true
# Customise browser size
# serenity.browser.height=1200
# serenity.browser.width=1200
output.formats=json,html
serenity.project.name=My Automation Project 
serenity.take.screenshots=FOR_FAILURES
serenity.use.unique.browser=true
story.timeout.in.secs=7200
serenity.restart.browser.for.each=story
serenity.compress.filenames=true
github.url=https://github.com/zhabieiev/myJavaTests.git
serenity.console.colors=true
serenity.report.show.manual.tests=true
serenity.logging=NORMAL