aws.login.type.default=SSO
aws.profile=sso-dev-account
interval.1.second=1000
interval.5.seconds=5000
interval.10.seconds=10000
interval.30.seconds=30000
interval.1.minute=60000
interval.2.minute=120000
interval.5.minutes=300000
interval.10.minutes=600000
path.file=src/test/resources/files
url.aqa=https://aqa.com
