package com.aqa.core.enumerations;

public enum Property implements PropertyReader {
    AWS_LOGIN_TYPE_DEFAULT,
    AWS_PROFILE,
    INTERVAL_1_SECOND,
    INTERVAL_5_SECONDS,
    INTERVAL_10_SECONDS,
    INTERVAL_30_SECONDS,
    INTERVAL_1_MINUTE,
    INTERVAL_2_MINUTE,
    INTERVAL_5_MINUTES,
    INTERVAL_10_MINUTES,
    PACKAGE_MODELS,
    USER_ADMINISTRATOR_EMAIL,
    USER_ADMINISTRATOR_NAME_FIRST,
    USER_ADMINISTRATOR_NAME_LAST,
    USER_ADMINISTRATOR_PASSWORD,
    USER_EMAIL,
    USER_PASSWORD,
    URL_API,
    URL_UI,
    V2;
}
